name: Flask CI/CD Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test-and-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
          
      - name: Install dependencies
        run: |
          pip install -r packages.txt
          
      - name: Run basic test
        run: |
          python -c "import flask; print(f'Flask version: {flask.__version__}')"
          
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
          
      - name: Build Docker image
        run: |
          docker build -t flask-app:latest .
          
      - name: Test Docker image
        run: |
          docker run --name test-flask -d -p 3000:3000 flask-app:latest
          sleep 5
          curl -f http://localhost:3000 || exit 1
          docker stop test-flask
          docker rm test-flask
  deploy:
    runs-on: ubuntu-latest
    needs: test-and-build
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Deploy to SSH host (пример)
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SSH_HOST: ${{ secrets.SSH_HOST }}
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_USER_GIT: ${{  secrets.SSH_USER_GIT }}
        run: |
          echo $(pwd)
          mkdir ~/.ssh
          chmod 700 ~/.ssh
          echo "$SSH_USER_GIT" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

          eval $(ssh-agent -s)
          ssh-add ~/.ssh/id_rsa

          echo $(ls -la ~)
          
          mkdir -p /opt/flask-app
          cd /opt/flask-app
          if [ ! -d .git ]; then
          git clone git@github.com:sheismycherrypie2-art/proj.git .
          fi
          git pull origin main
          docker stop flask-app || true
          docker rm flask-app || true
          docker build -t flask-app .
          docker run -d --name flask-app -p 3000:3000 flask-app
